### ISSUE TITLE
UiGrid anomalies

### ISSUE THREAD

**Issue by kavi87** [seedstack/w20#3]
UiGrid module in w20 suffer from severall issues:

- [x] Column resizing distorts the grid.
- [x] Setting the height of the grid dynamically cause it to fluctuate anormally.
- [x] The grid does not resize itself when a side menu is toggled.
- [x] The "Select all rows" options does not seem to work even if the option is specified.
- [x]  If we scroll the grid down and then navigate to another page and come back to the grid again without refreshing. In this case the top(scrolled) portion of the grid becomes blank. If we scroll again it comes back normal (IE only).

**Comment by kavi87** [comment]
N°3 : "The grid does not resize itself when a side menu is toggled." : Fixed by adding dependency module  'ui.grid.autoResize' to grid.js. Using projects will need to add the directive 'data-ui-grid-auto-resize' to their grid element in order for it to fix the issue.

**Comment by kavi87** [comment]
N°4: "The 'Select all rows' options does not seem to work even if the option is specified.": Fixed by adding dependency module 'ui.grid.selection' to grid.js. Using project will need to add the directive 'data-ui-grid-selection' to their grid element in order for it to fix the issue.

**Comment by kavi87** [comment]
N°2: "Setting the height of the grid dynamically cause it to fluctuate anormally.": This appear while using Jquery for setting the height of the grid and calling handleWindowResize() thereafter. It might simply need an $apply() somewhere or perhaps setting dynamically the height is simply just a bad idea.

**Comment by kavi87** [comment]
N°5: "If we scroll the grid down and then navigate to another page [...]": Cannot fix. This seems a specific issue related to how IE 9 redraw canvas, it could be fixed in new version of the grid in the future.

**Comment by kavi87** [comment]
N°1: "Column resizing distorts the grid.": Cannot reproduced. Will need to see an example but is unlikely to be fixed.

**Comment by aritrabasu104** [comment]
I have resolved the third issue by reloading the page on grid toggle
The same should work for 1 and 2

**Comment by aritrabasu104** [comment]
The select all row is working fine
