### ISSUE TITLE
Piwik module not working with last version of Piwik

### ISSUE THREAD

**Issue by kavi87** [seedstack/w20#5]
The last version of Piwik does not seem to work with the piwik module in fragment extra. 
It should be fixed or perhaps we should consider switching to a solution like angulartics.

**Comment by adrienlauer** [comment]
Switching to Angulartics seems to be the sensible thing to do to me. It appears very complete and will enable to handle multiple providers. Not sure which integration value we could add on top of it tough.

**Comment by kavi87** [comment]
Ok then, maybe we can integrate Angulartic with a default configuration that user can override/extend.
