### ISSUE TITLE
Improve unit test coverage

### ISSUE THREAD

**Issue by kavi87** [seedstack/w20#8]
Everything is in the title.

**Comment by pith** [comment]
It may also be useful to add the integration of Coveralls for W20 and others SeedStack JS projects as we did for Java ones.

See this for the intergration: https://github.com/pimterry/grunt-coveralls

> Grunt task to load coverage results and submit them to Coveralls.io

**Comment by kavi87** [comment]
Agree, it will provide a nice centralized place for all the code base.
