### ISSUE TITLE
UI Bootstrap 0.12.0 not working with Angular 1.3.6

### ISSUE THREAD

**Issue by kavi87** [seedstack/w20#9]
This [thread](https://github.com/angular-ui/bootstrap/issues/2156) shows that the ui bootstrap team are struggling with an integration with angular > 1.3.x. Not sure how things are going on right now. Bottom line, currently the last version of ui bootstrap (0.12.0) does not work with our version of angular (1.3.6). We should probably downgrade it to 0.10.0.

**Comment by adrienlauer** [comment]
They release a 0.13 version which is compatible with angular 1.3.x. Too bad Angular 1.4.0 was just released a few weeks ago :)

**Comment by syedamir91** [comment]
for me the following version of angular and ui-bootstrap is not compatible:

http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js
https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.13.0/ui-bootstrap-tpls.js

![image](https://user-images.githubusercontent.com/7950345/32283350-13c7f05a-bf4a-11e7-9cd7-92d8bbfd007d.png)
